### ISSUE TITLE
Storage Visibility set as public 

### ISSUE THREAD

**Issue by imrantune** [exula/laravel-storage-rados-s3#1]
Hi @exula sir,

Thanks for this repo its really helping me to integrate ceph as S3 storage. 

I am facing a issue when I used only aws-s3 Visibility  setting applied from configuration but when I used  this repos [laravel-storage-rados-s3] its working fine only not getting the setting of Visibility always set as private 

I tried both 

```
'base_url' => env('CEPH_BASE_URL', 'https://s3.url'),
            'driver' => 'ceph',
            'key' => env('CEPH_ACCESS_KEY', 'xxxxxxxxxxx'),
            'credentials' => [
                'key' => env('CEPH_ACCESS_KEY', 'xxxxxxxxxxxxxxxxxx'),
                'secret' => env('CEPH_SECRET_KEY', 'xxxxxxxxxxxxxxxxxxxxxxxxxxx'),
                'visibility' => 'public',
            ],
            'region' => '',
            'bucket' => env('CEPH_BUCKET', 'panther-new-bucket'),
            'version' => 'latest',
            'visibility' => 'public',
```
`visibility` are not working as configured 

Can you help me ?

**Comment by imrantune** [comment]
@exula Thanks I got the point 
me added some more options in mine fork repo now its working 

Thansk :)

**Comment by exula** [comment]
Hello, I'd love to see what you had to change to get this working, I've seen some problems like this before. 

My solution was always to explicitly set the visibility in my application code. 

Can you make a pull request so I can merge what you did? 

Thanks!

**Comment by imrantune** [comment]
@exula 
Please check the pull request

**Comment by exula** [comment]
@imrantune I've gone ahead and merged. 
Just out of curiosity, what version of Laravel are you using this repo in?

**Comment by imrantune** [comment]
> @imrantune I've gone ahead and merged.
> Just out of curiosity, what version of Laravel are you using this repo in?

6.20.9

**Comment by exula** [comment]
Thanks!

**Comment by imrantune** [comment]
Hi @exula .

Hope you are doing well

can you please a new release with latest changing 
its now updated in composer
